// <auto-generated />
using System;
using AvivCRM.Environment.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvivCRM.Environment.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnvironmentDbContext))]
    [Migration("20250110092021_Sivan-RecruitFooter_Table_ColumnName_Renamed")]
    partial class SivanRecruitFooter_Table_ColumnName_Renamed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("aviv")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Applications", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DatatableRowLimit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultTimezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmployeeCanExportData")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeFormat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("tblApplication", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.AttendanceSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttendanceSettingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttendanceSettingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblAttendanceSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("tblClient", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContractNumberDigits")
                        .HasColumnType("int");

                    b.Property<string>("ContractNumberExample")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractNumberSeprator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblContract", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecimalSeparator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExchangeRate")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IsCryptocurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberofDecimals")
                        .HasColumnType("int");

                    b.Property<string>("ThousandSeparator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("USDPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblCurrency", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.CustomQuestionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblCustomQuestionCategory", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.CustomQuestionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblCustomQuestionType", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("tblEmployee", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.FinanceInvoiceSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FIAuthorisedImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIAuthorisedImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FICBClientInfoJsonSettings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FICBGeneralJsonSettings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FIDueAfter")
                        .HasColumnType("int");

                    b.Property<Guid>("FILanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FILogoImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FILogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIOtherInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FISendReminderAfterEvery")
                        .HasColumnType("int");

                    b.Property<int>("FISendReminderAfterEveryId")
                        .HasColumnType("int");

                    b.Property<int>("FISendReminderBefore")
                        .HasColumnType("int");

                    b.Property<string>("FITerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblFinanceInvoiceSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.FinanceInvoiceTemplateSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FIRBTemplateJsonSettings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblFinanceInvoiceTemplateSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.FinancePrefixSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FICBPrefixJsonSettings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblFinancePrefixSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.FinanceUnitSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblFinanceUnitSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.JobApplicationCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblJobApplicationCategory", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.JobApplicationPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblJobApplicationPosition", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblLanguage", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.LeadAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblLeadAgent", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.LeadCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblLeadCategory", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.LeadSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblLeadSource", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.LeadStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblLeadStatus", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("All")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowChatClientEmployee")
                        .HasColumnType("bit");

                    b.Property<bool>("Allowchatclientadmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OnlyProjectMembercanwithclient")
                        .HasColumnType("bit");

                    b.Property<bool>("SoundNotifyAlert")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tblMessage", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AgentTicket")
                        .HasColumnType("bit");

                    b.Property<bool>("AttendanceReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoTaskReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("ContractSigned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmployeeAssigntoProject")
                        .HasColumnType("bit");

                    b.Property<bool>("EstimateDeclined")
                        .HasColumnType("bit");

                    b.Property<bool>("EventInvite")
                        .HasColumnType("bit");

                    b.Property<bool>("EventReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("FollowUpReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("InvoiceCreated")
                        .HasColumnType("bit");

                    b.Property<bool>("InvoiceReminder")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("Leadnotification")
                        .HasColumnType("bit");

                    b.Property<bool>("LeaveApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("LeaveRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("LeaveUpdated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ModulesEmailNotificationAttendanceReminderNew")
                        .HasColumnType("bit");

                    b.Property<bool>("ModulesEmailNotificationEventInviteNew")
                        .HasColumnType("bit");

                    b.Property<bool>("ModulesEmailNotificationEventReminderNew")
                        .HasColumnType("bit");

                    b.Property<bool>("ModulesEmailNotificationTestNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("MultipleLeaveApplication")
                        .HasColumnType("bit");

                    b.Property<bool>("NewClientTask")
                        .HasColumnType("bit");

                    b.Property<bool>("NewExpenseAddedbyAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("NewExpenseAddedbyMember")
                        .HasColumnType("bit");

                    b.Property<bool>("NewFileUploadedtoProject")
                        .HasColumnType("bit");

                    b.Property<bool>("NewLeaveApplication")
                        .HasColumnType("bit");

                    b.Property<bool>("NewLeaveRequest")
                        .HasColumnType("bit");

                    b.Property<bool>("NewMultipleLeaveApplication")
                        .HasColumnType("bit");

                    b.Property<bool>("NewNoticePublished")
                        .HasColumnType("bit");

                    b.Property<bool>("NewOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("NewPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("NewProductPurchase")
                        .HasColumnType("bit");

                    b.Property<bool>("NewProject")
                        .HasColumnType("bit");

                    b.Property<bool>("NewPropoInvoiceUpdatedsal")
                        .HasColumnType("bit");

                    b.Property<bool>("NewProposal")
                        .HasColumnType("bit");

                    b.Property<bool>("NewRecurringInvoice")
                        .HasColumnType("bit");

                    b.Property<bool>("NewSupportTicketRequest")
                        .HasColumnType("bit");

                    b.Property<bool>("NewTask")
                        .HasColumnType("bit");

                    b.Property<bool>("NewTicketReply")
                        .HasColumnType("bit");

                    b.Property<bool>("NewTicketRequest")
                        .HasColumnType("bit");

                    b.Property<bool>("NoticeUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("OrderUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("PaymentReceived")
                        .HasColumnType("bit");

                    b.Property<bool>("PaymentReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("ProjectReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("ProposalApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("ProposalRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("RecurringExpenseStatusUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("RecurringInvoiceStatusUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestAdminNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestApprovedLead")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestApprovedUser")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestReject")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestRejectLead")
                        .HasColumnType("bit");

                    b.Property<bool>("RemovalRequestRejectUser")
                        .HasColumnType("bit");

                    b.Property<bool>("SubTaskAssigneeAdded")
                        .HasColumnType("bit");

                    b.Property<bool>("SubTaskCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskComment")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskCompletedClient")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskNote")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskUpdateClient")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskUpdated")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorCode")
                        .HasColumnType("bit");

                    b.Property<bool>("UserJoinViaInvitation")
                        .HasColumnType("bit");

                    b.Property<bool>("UserRegistrationAddedbyAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tblNotification", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.NotificationMain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommonNotificationMainJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNotificationMainJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveNotificationMainJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentNotificationMainJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNotificationMainJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposalNotificationMainJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReminderNotificationMainJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestNotificationMainJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskNotificationMainJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNotificationMainJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblNotificationMain", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblPayment", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Planning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Designation")
                        .HasColumnType("int");

                    b.Property<int>("Employee")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<float>("PlanPrice")
                        .HasColumnType("real");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<int>("Validity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblPlanning", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.ProjectCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblProjectCategory", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.ProjectReminderPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblProjectReminderPerson", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.ProjectSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSendReminder")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectReminderPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RemindBefore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblProjectSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.ProjectStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefaultStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tblProjectStatus", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.PurchaseSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchasePrefixJsonSettings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblPurchaseSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.RecruitCustomQuestionSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("tblRecruitCustomQuestionSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.RecruitFooterSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblRecruitFooterSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.RecruitGeneralSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BGColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BGLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BGLogoImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BGLogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CBJsonSettings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuplJobApplnRestrictDays")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LegalTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OLReminderToCandidate")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblRecruitGeneralSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.RecruitJobApplicationStatusSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModelChecked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblRecruitJobApplicationStatusSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.RecruitNotificationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMailJsonSettings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMailNotificationJsonSettings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblRecruitNotificationSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.RecruiterSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tblRecruiterSetting", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Tasks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AddFile")
                        .HasColumnType("bit");

                    b.Property<int>("AfterXDate")
                        .HasColumnType("int");

                    b.Property<bool>("AssignedBy")
                        .HasColumnType("bit");

                    b.Property<bool>("AssignedTo")
                        .HasColumnType("bit");

                    b.Property<int>("BeforeXDate")
                        .HasColumnType("int");

                    b.Property<bool>("Comment")
                        .HasColumnType("bit");

                    b.Property<bool>("CopyTaskLink")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CustomFields")
                        .HasColumnType("bit");

                    b.Property<bool>("Description")
                        .HasColumnType("bit");

                    b.Property<bool>("DueDate")
                        .HasColumnType("bit");

                    b.Property<bool>("History")
                        .HasColumnType("bit");

                    b.Property<bool>("HoursLogged")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("Label")
                        .HasColumnType("bit");

                    b.Property<bool>("MakePrivate")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Notes")
                        .HasColumnType("bit");

                    b.Property<bool>("Priority")
                        .HasColumnType("bit");

                    b.Property<bool>("Project")
                        .HasColumnType("bit");

                    b.Property<bool>("SendReminderDueDate")
                        .HasColumnType("bit");

                    b.Property<bool>("StartDate")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Statuss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SubTask")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskCategory")
                        .HasColumnType("bit");

                    b.Property<int>("TaskboardLength")
                        .HasColumnType("int");

                    b.Property<bool>("TimeEstimate")
                        .HasColumnType("bit");

                    b.Property<bool>("Timesheet")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tblTask", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Tax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("tblTax", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.TicketAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblTicketAgent", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.TicketChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblTicketChannel", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.TicketGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblTicketGroup", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.TicketReplyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblTicketReplyTemplate", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.TicketType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblTicketType", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.TimeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CBTimeLogJsonSettings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDailyTimeLogReportEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTimeTrackerReminderEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TLTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblTimeLog", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Timesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Memo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblTimesheet", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.ToggleValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblToggleValue", "aviv");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Applications", b =>
                {
                    b.HasOne("AvivCRM.Environment.Domain.Entities.Currency", "Currency")
                        .WithMany("Application")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("AvivCRM.Environment.Domain.Entities.Currency", b =>
                {
                    b.Navigation("Application");
                });
#pragma warning restore 612, 618
        }
    }
}
